version: "3"
services:
  web:
    image: whonselaar/messageprocessor:v1.0.1
    environment:
      - 192.168.10.203 rabbitmq rabbitmq
    deploy:
      #replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - webnet
networks:
  webnet: