version: "3.2"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: whonselaar/messageprocessor:v1.0.1
	environment:
	  - address:"localhost"
	  - username:"guest"
	  - password:"guest"
    deploy:
      replicas: 5
      #resources:
        #limits:
          #cpus: "0.1"
          #memory: 200m
      restart_policy:
        condition: on-failure
    networks:
      - webnet
networks:
  webnet: