version: "3"

services:
  rabbits:
    image: rabbitmq:3-management
    deploy:
      restart_policy:
        condition: on-failure
    hostname: rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: rabbitmq1
    networks:
      - webnet
networks:
  webnet: